"""Download Materials Project structures for oxide screening.

Reads composition_list.xlsx (generated by 01_compositions.py) and downloads
DFT structures from the Materials Project for every chemical system in the list.
Works for any configured chemistry and crystal prototype.

Requires a valid Materials Project API key:
    pip install mp-api

Output (written to BLADE/Files/MaterialsProject_Comps/):
    <chemsys>/<material_id>_<formula>/POSCAR
    materials_project_summary.xlsx
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
from mp_api.client import MPRester
from pymatgen.io.vasp import Poscar

# ------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------
path0 = Path("/Users/chasekatz/Desktop/School/Research")
path1 = path0 / "BLADE"

files_dir = path1 / "Files"
files_dir.mkdir(parents=True, exist_ok=True)

mp_comps_dir = files_dir / "MaterialsProject_Comps_POSCARs"


# ==============================================================================
# Section 2a: Download Materials Project structures (run once with API key)
# Requires: pip install mp-api
# ==============================================================================
API_KEY = os.environ.get("MP_API_KEY", "").strip()
if not API_KEY:
    raise RuntimeError("Set MP_API_KEY before running this Materials Project download example.")
composition_xlsx = files_dir / "composition_list.xlsx"

# Set True to download only thermodynamically stable phases (energy_above_hull == 0)
stable_only = True

# Skip MP download for formulas already in BLADE database (BLADE's relaxed
# structures take precedence over MP DFT structures for those compositions)
skip_blade_formulas = True
blade_xlsx = files_dir / "blade_generated_data.xlsx"
_blade_formulas: set[str] = set()
if skip_blade_formulas and blade_xlsx.exists():
    import pandas as _pd
    from pymatgen.core import Composition as _Comp

    _bdf = _pd.read_excel(blade_xlsx)
    for f in _bdf.get("formula", _pd.Series(dtype=str)).dropna():
        try:
            _blade_formulas.add(_Comp(str(f)).reduced_formula)
        except Exception:
            pass
    print(f"Loaded {len(_blade_formulas)} BLADE formulas to skip")

df_comps = pd.read_excel(composition_xlsx)
systems = []
for _, row in df_comps.iterrows():
    elements = [x.strip() for x in str(row["elements"]).split(",") if x.strip()]
    if not elements:
        continue
    chemsys = "-".join(sorted(elements))
    systems.append(
        {
            "composition": row["composition"],
            "metal_composition": row.get("metal_composition", ""),
            "both_composition": row.get("both_composition", ""),
            "chemsys": chemsys,
            "elements": elements,
        }
    )

systems_df = pd.DataFrame(systems).drop_duplicates(subset=["chemsys"])

fields = [
    "material_id",
    "formula_pretty",
    "composition_reduced",
    "energy_per_atom",
    "formation_energy_per_atom",
    "energy_above_hull",
    "is_stable",
    "volume",
    "density",
    "nsites",
    "symmetry",
    "structure",
]

summary_rows = []
with MPRester(API_KEY) as mpr:
    for _, sysrow in systems_df.iterrows():
        chemsys = sysrow["chemsys"]
        print(f"Searching Materials Project: {chemsys}")
        try:
            docs = mpr.materials.summary.search(
                chemsys=chemsys,
                is_stable=True if stable_only else None,
                fields=fields,
            )
        except Exception as e:
            print(f"Failed for {chemsys}: {e}")
            continue

        chemsys_dir = mp_comps_dir / chemsys
        chemsys_dir.mkdir(parents=True, exist_ok=True)
        n_saved = 0

        for doc in docs:
            # Skip if this formula is already in the BLADE database
            if skip_blade_formulas and _blade_formulas:
                try:
                    from pymatgen.core import Composition as _C

                    reduced = _C(doc.formula_pretty).reduced_formula
                except Exception:
                    reduced = doc.formula_pretty
                if reduced in _blade_formulas:
                    print(f"  Skipping {doc.formula_pretty} — already in BLADE database")
                    continue

            mat_dir = chemsys_dir / f"{doc.material_id}_{doc.formula_pretty}"
            mat_dir.mkdir(parents=True, exist_ok=True)
            poscar_path = mat_dir / "POSCAR"
            Poscar(doc.structure).write_file(poscar_path)
            n_saved += 1

            sym = doc.symmetry
            summary_rows.append(
                {
                    "input_composition": sysrow["composition"],
                    "input_metal_composition": sysrow["metal_composition"],
                    "input_both_composition": sysrow["both_composition"],
                    "chemsys": chemsys,
                    "material_id": str(doc.material_id),
                    "formula": doc.formula_pretty,
                    "energy_per_atom": doc.energy_per_atom,
                    "formation_energy_per_atom": doc.formation_energy_per_atom,
                    "energy_above_hull": doc.energy_above_hull,
                    "is_stable": doc.is_stable,
                    "volume": doc.volume,
                    "volume_per_atom": doc.volume / doc.nsites if doc.nsites else None,
                    "density": doc.density,
                    "nsites": doc.nsites,
                    "crystal_system": getattr(sym, "crystal_system", None),
                    "spacegroup_number": getattr(sym, "number", None),
                    "spacegroup_symbol": getattr(sym, "symbol", None),
                    "poscar_path": str(poscar_path),
                }
            )

        if n_saved == 0 and chemsys_dir.exists() and not any(chemsys_dir.iterdir()):
            chemsys_dir.rmdir()
            print(f"  No structures found — removed empty dir: {chemsys}")

pd.DataFrame(summary_rows).to_excel(mp_comps_dir / "materials_project_summary.xlsx", index=False)
print(f"Saved POSCARs under: {mp_comps_dir}")
